// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../common/Utils.js";
import Link from "next/link";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as JsxRuntime from "react/jsx-runtime";

let defaultImage = "https://image.ausha.co/y16tcxiM957ICPP3MtB2HvmB9ot3e5di2OiKSMMd_400x400.jpeg";

function EpisodCard(props) {
  let match = props.episod;
  return JsxRuntime.jsx(Link, {
    href: `/episode/` + match.public_id,
    children: JsxRuntime.jsxs("a", {
      children: [
        JsxRuntime.jsx("img", {
          className: "object-contain p-5",
          src: Stdlib_Option.getOr(match.image_url, defaultImage)
        }),
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("div", {
              children: Utils.s(match.published_at.toLocaleDateString(undefined, {month: 'short', year: 'numeric'})),
              className: "text-gray-500 capitalize font-display"
            }),
            JsxRuntime.jsx("div", {
              children: Utils.s(match.name),
              className: "text-gray-700"
            })
          ],
          className: "flex-auto px-5 pb-5"
        })
      ],
      className: "max-w-sm overflow-hidden flex flex-col items-center bg-gray-100 shadow-2xl hover:opacity-75"
    })
  });
}

let make = EpisodCard;

export {
  defaultImage,
  make,
}
/* next/link Not a pure module */
