// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.js";
import * as Api from "../../common/Api.js";
import * as Index from "../index.js";
import * as Utils from "../../common/Utils.js";
import Head from "next/head";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function $lbrackpublic_id$rbrack$Player(props) {
  let code = `<iframe frameborder="0" loading="lazy" id="ausha-dwpf" height="220" style="border: none; width:100%; height:220px" src="https://player.ausha.co/index.html?showId=od2PjTvjJpwV&color=%239b4d1c&podcastId=` + props.public_id + `&v=3&playerId=ausha-dwpf"></iframe><script src="https://player.ausha.co/ausha-player.js"></script>
`;
  return JsxRuntime.jsx("div", {
    className: "mt-5",
    dangerouslySetInnerHTML: {
      __html: code
    }
  });
}

function $$default(param) {
  let val;
  try {
    val = S.parseJsonOrThrow(param.episod, Api.Podcast.SingleByPublicId.schema);
  } catch (raw_e) {
    let e = Primitive_exceptions.internalToException(raw_e);
    if (e.RE_EXN_ID === S.$$Error) {
      console.error("an error occurred while loading the podcast", e._1);
      return JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h1", {
            children: Utils.s(`Ouups !!`)
          }),
          JsxRuntime.jsx("p", {
            children: Utils.s(`Il y a eu une erreur lors de la récupération de l'épisode, veuillez réessayer.`)
          })
        ]
      });
    }
    throw e;
  }
  let match = val.data;
  let image_url = match.image_url;
  let html_description = match.html_description;
  let description = match.description;
  let name = match.name;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs(Head, {
        children: [
          JsxRuntime.jsx("title", {
            children: Utils.s(name)
          }),
          JsxRuntime.jsx("meta", {
            content: "width=device-width, initial-scale=1",
            name: "viewport"
          }),
          JsxRuntime.jsx("meta", {
            charSet: "utf-8"
          }),
          description !== undefined ? JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx("meta", {
                  content: description,
                  name: "description"
                }),
                JsxRuntime.jsx("meta", {
                  content: description,
                  property: "og:description"
                }, "ogdesc")
              ]
            }) : null,
          JsxRuntime.jsx("meta", {
            content: name,
            property: "og:title"
          }, "ogtitle"),
          image_url !== undefined ? JsxRuntime.jsx("meta", {
              content: image_url,
              property: "og:image"
            }, "ogimage") : null,
          JsxRuntime.jsx("meta", {
            content: Index.siteName,
            property: "og:site_name"
          }, "ogsitename"),
          JsxRuntime.jsx("meta", {
            content: "summary",
            name: "twitter:card"
          }, "twcard")
        ]
      }),
      JsxRuntime.jsx($lbrackpublic_id$rbrack$Player, {
        public_id: match.public_id
      }),
      html_description !== undefined ? JsxRuntime.jsx("div", {
          className: "text-justify m-3 text-gray-800 space-y-5",
          dangerouslySetInnerHTML: {
            __html: html_description
          }
        }) : null
    ]
  });
}

async function getServerSideProps(param) {
  let public_id = Stdlib_Option.getOrThrow(param.query["public_id"], undefined);
  let episod = await Api.Podcast.SingleByPublicId.get(public_id);
  return {
    props: {
      episod: episod
    }
  };
}

export {
  $$default as default,
  getServerSideProps,
}
/* S Not a pure module */
