// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.js";
import * as NodeFetch from "node-fetch";

let baseUrl = "https://developers.ausha.co";

let showId = "32899";

function get(url) {
  return NodeFetch(url, {
    headers: {
      accept: "application/json",
      "content-type": "application/json",
      Authorization: `Bearer ` + process.env.AUSHA_TOKEN
    }
  });
}

let schema = S.datetime(S.string, undefined);

let IsoDate = {
  schema: schema
};

let paginationSchema = S.schema(s => ({
  total: s.m(S.int),
  count: s.m(S.int),
  per_page: s.m(S.int),
  current_page: s.m(S.int),
  total_pages: s.m(S.int)
}));

let metaSchema = S.schema(s => ({
  pagination: s.m(paginationSchema)
}));

let linksSchema = S.schema(s => ({
  self: s.m(S.string),
  first: s.m(S.string),
  prev: s.m(S.nullableAsOption(S.string)),
  next: s.m(S.nullableAsOption(S.string)),
  last: s.m(S.string)
}));

function dataSchema(paramSchema) {
  return S.schema(s => ({
    data: s.m(S.array(paramSchema)),
    meta: s.m(metaSchema)
  }));
}

function simpleDataSchema(paramSchema) {
  return S.schema(s => ({
    data: s.m(paramSchema)
  }));
}

function arrayDataSchema(paramSchema) {
  return S.schema(s => ({
    data: s.m(S.array(paramSchema))
  }));
}

let Common = {
  paginationSchema: paginationSchema,
  metaSchema: metaSchema,
  linksSchema: linksSchema,
  dataSchema: dataSchema,
  simpleDataSchema: simpleDataSchema,
  arrayDataSchema: arrayDataSchema
};

let schema$1 = S.schema(s => ({
  key: s.m(S.string),
  url: s.m(S.string)
}));

let Link = {
  schema: schema$1
};

let schema$2 = S.union([
  S.literal("full"),
  S.literal("bonus"),
  S.literal("trailer")
]);

let Type = {
  schema: schema$2
};

let schema$3 = S.union([
  S.literal("public"),
  S.literal("private"),
  S.literal("unlisted")
]);

let Privacy = {
  schema: schema$3
};

let schema$4 = S.union([
  S.literal("draft"),
  S.literal("blocked"),
  S.literal("active"),
  S.literal("scheduled")
]);

let State = {
  schema: schema$4
};

let schema$5 = S.union([
  S.literal("facebook"),
  S.literal("twitter"),
  S.literal("newsletter")
]);

let AutoSharing = {
  schema: schema$5
};

let tagSchema = S.schema(s => ({
  id: s.m(S.int),
  slug: s.m(S.string),
  name: s.m(S.string)
}));

let fileSchema = S.schema(s => ({
  format: s.m(S.string),
  key: s.m(S.string),
  mime_type: s.m(S.string),
  duration: s.m(S.float)
}));

let tagsSchema = arrayDataSchema(tagSchema);

let filesSchema = arrayDataSchema(fileSchema);

let schema$6 = S.schema(s => ({
  id: s.m(S.int),
  show_id: s.m(S.int),
  type: s.m(schema$2),
  season_id: s.m(S.nullableAsOption(S.int)),
  name: s.m(S.string),
  public_id: s.m(S.string),
  guid: s.m(S.string),
  slug: s.m(S.string),
  description: s.m(S.nullableAsOption(S.string)),
  html_description: s.m(S.nullableAsOption(S.string)),
  privacy: s.m(schema$3),
  state: s.m(schema$4),
  is_explicit: s.m(S.bool),
  can_download: s.m(S.bool),
  duration: s.m(S.float),
  image_url: s.m(S.nullableAsOption(S.string)),
  audio_url: s.m(S.string),
  site_url: s.m(S.nullableAsOption(S.string)),
  smartlink_url: s.m(S.string),
  waveform_url: s.m(S.string),
  downloads_count: s.m(S.int),
  published_at: s.m(schema),
  created_at: s.m(schema),
  updated_at: s.m(schema),
  tags: s.m(tagsSchema),
  files: s.m(filesSchema)
}));

let schema$7 = simpleDataSchema(schema$6);

async function get$1(public_id) {
  let url = baseUrl + `/v1/podcasts/public_id/` + public_id;
  let response = await get(url);
  return await response.json();
}

let SingleByPublicId = {
  schema: schema$7,
  get: get$1
};

let Podcast = {
  Type: Type,
  Privacy: Privacy,
  State: State,
  AutoSharing: AutoSharing,
  tagSchema: tagSchema,
  fileSchema: fileSchema,
  tagsSchema: tagsSchema,
  filesSchema: filesSchema,
  schema: schema$6,
  SingleByPublicId: SingleByPublicId
};

let schema$8 = dataSchema(schema$6);

async function get$2(publicOpt, private_Opt, unlistedOpt, activeOpt, draftOpt, scheduledOpt, param) {
  let $$public = publicOpt !== undefined ? publicOpt : false;
  let private_ = private_Opt !== undefined ? private_Opt : false;
  let unlisted = unlistedOpt !== undefined ? unlistedOpt : false;
  let active = activeOpt !== undefined ? activeOpt : false;
  let draft = draftOpt !== undefined ? draftOpt : false;
  let scheduled = scheduledOpt !== undefined ? scheduledOpt : false;
  let statuses = [];
  if ($$public) {
    statuses.push("public");
  }
  if (private_) {
    statuses.push("private");
  }
  if (unlisted) {
    statuses.push("unlisted");
  }
  if (active) {
    statuses.push("active");
  }
  if (draft) {
    statuses.push("draft");
  }
  if (scheduled) {
    statuses.push("scheduled");
  }
  let queryString = statuses.length !== 0 ? "?" + statuses.map(status => `status[]=` + status).join("&") : "";
  let url = baseUrl + `/v1/shows/` + showId + `/podcasts` + queryString;
  let response = await get(url);
  return await response.json();
}

let Podcasts = {
  schema: schema$8,
  get: get$2
};

let listeningLinksSchema = arrayDataSchema(schema$1);

let schema$9 = S.schema(s => ({
  description: s.m(S.string),
  html_description: s.m(S.string),
  image_url: s.m(S.string),
  listening_links: s.m(listeningLinksSchema)
}));

let Show = {
  listeningLinksSchema: listeningLinksSchema,
  schema: schema$9
};

let schema$10 = simpleDataSchema(schema$9);

async function get$3() {
  let url = baseUrl + `/v1/shows/` + showId;
  let response = await get(url);
  return await response.json();
}

let SingleById = {
  schema: schema$10,
  get: get$3
};

let Shows = {
  SingleById: SingleById
};

export {
  baseUrl,
  showId,
  get,
  IsoDate,
  Common,
  Link,
  Podcast,
  Podcasts,
  Show,
  Shows,
}
/* schema Not a pure module */
