// Generated by ReScript, PLEASE EDIT WITH CARE

import Link from "next/link";
import * as JsxRuntime from "react/jsx-runtime";

function MainLayout$Icon(props) {
  return JsxRuntime.jsx("a", {
    children: props.children,
    className: "px-1 opacity-75 hover:opacity-50",
    href: props.link,
    target: "_blank"
  });
}

let Icon = {
  make: MainLayout$Icon
};

function MainLayout$Navigation(props) {
  return JsxRuntime.jsxs("nav", {
    children: [
      JsxRuntime.jsx(Link, {
        href: "/",
        children: JsxRuntime.jsx("a", {
          children: JsxRuntime.jsx("span", {
            children: `Goutues`,
            className: "text-brown text-4xl md:text-5xl font-semibold font-logo"
          })
        })
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: JsxRuntime.jsx(Link, {
              href: "/episodes",
              children: JsxRuntime.jsx("a", {
                children: `Épisodes`
              })
            }),
            className: "px-3 font-display hover:opacity-75"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx(MainLayout$Icon, {
                link: "https://facebook.com/goutues",
                children: JsxRuntime.jsx("img", {
                  className: "h-6",
                  src: "/static/ri-facebook-circle-line.svg"
                })
              }),
              JsxRuntime.jsx(MainLayout$Icon, {
                link: "https://www.instagram.com/goutues/",
                children: JsxRuntime.jsx("img", {
                  className: "h-6",
                  src: "/static/ri-instagram-line.svg"
                })
              }),
              JsxRuntime.jsx(MainLayout$Icon, {
                link: "https://podcast.ausha.co/goutues",
                children: JsxRuntime.jsx("img", {
                  className: "w-16",
                  src: "/static/ausha.svg"
                })
              })
            ],
            className: "flex flex-row items-center"
          })
        ],
        className: "flex items-center"
      })
    ],
    className: "px-2 pt-1 pb-2 flex border-b-4 mb-10 border-yellow justify-between items-baseline text-lg"
  });
}

let Navigation = {
  make: MainLayout$Navigation
};

function MainLayout(props) {
  return JsxRuntime.jsx("div", {
    children: JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx(MainLayout$Navigation, {}),
        JsxRuntime.jsx("main", {
          children: props.children,
          className: "my-4"
        })
      ],
      className: "max-w-5xl w-full lg:w-3/4 text-gray-700 font-base"
    }),
    className: "flex lg:justify-center",
    style: {
      minWidth: "20rem"
    }
  });
}

let Link$1;

let make = MainLayout;

export {
  Link$1 as Link,
  Icon,
  Navigation,
  make,
}
/* next/link Not a pure module */
