// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as MainLayout from "../layouts/MainLayout.js";
import * as Router from "next/router";
import * as JsxRuntime from "react/jsx-runtime";

import '../styles/main.css'
;

function $$default(props) {
  let router = Router.useRouter();
  let content = React.createElement(props.Component, props.pageProps);
  let match = router.route;
  switch (match) {
    default:
      return JsxRuntime.jsx(MainLayout.make, {
        children: content
      });
  }
}

export {
  $$default as default,
}
/*  Not a pure module */
