// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.js";
import * as Api from "../common/Api.js";
import * as Index from "./index.js";
import * as Utils from "../common/Utils.js";
import Head from "next/head";
import * as EpisodCard from "../components/EpisodCard.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function $$default(param) {
  let val;
  let val$1;
  try {
    val = S.parseJsonOrThrow(param.episods, Api.Podcasts.schema);
    val$1 = S.parseJsonOrThrow(param.show, Api.Shows.SingleById.schema);
  } catch (raw_e) {
    let e = Primitive_exceptions.internalToException(raw_e);
    if (e.RE_EXN_ID === S.$$Error) {
      console.error("an error occurred while loading the podcasts", e._1);
      return JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h1", {
            children: Utils.s(`Ouups !!`)
          }),
          JsxRuntime.jsx("p", {
            children: Utils.s(`Il y a eu une erreur lors de la récupération des épisodes, veuillez réessayer.`)
          })
        ]
      });
    }
    throw e;
  }
  let match = val$1.data;
  let description = match.description;
  let title = `Goûtues - Épisodes`;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs(Head, {
        children: [
          JsxRuntime.jsx("title", {
            children: Utils.s(title)
          }),
          JsxRuntime.jsx("meta", {
            content: "width=device-width, initial-scale=1",
            name: "viewport"
          }),
          JsxRuntime.jsx("meta", {
            charSet: "utf-8"
          }),
          JsxRuntime.jsx("meta", {
            content: description,
            name: "description"
          }),
          JsxRuntime.jsx("meta", {
            content: title,
            property: "og:title"
          }, "ogtitle"),
          JsxRuntime.jsx("meta", {
            content: match.image_url,
            property: "og:image"
          }, "ogimage"),
          JsxRuntime.jsx("meta", {
            content: Index.siteName,
            property: "og:site_name"
          }, "ogsitename"),
          JsxRuntime.jsx("meta", {
            content: description,
            property: "og:description"
          }, "ogdesc"),
          JsxRuntime.jsx("meta", {
            content: "summary",
            name: "twitter:card"
          }, "twcard")
        ]
      }),
      val.data.map(episod => JsxRuntime.jsx(EpisodCard.make, {
        episod: episod
      }, episod.public_id)).toReversed()
    ],
    className: "justify-items-center p-2 gap-5 md:gap-10 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3"
  });
}

async function getServerSideProps(_ctx) {
  let episods = await Api.Podcasts.get(true, undefined, undefined, undefined, undefined, undefined, undefined);
  let show = await Api.Shows.SingleById.get();
  return {
    props: {
      episods: episods,
      show: show
    }
  };
}

export {
  $$default as default,
  getServerSideProps,
}
/* S Not a pure module */
