// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.js";
import * as Api from "../common/Api.js";
import * as Utils from "../common/Utils.js";
import Head from "next/head";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function Index$P(props) {
  return JsxRuntime.jsx("p", {
    children: props.children,
    className: "mb-2"
  });
}

function Index$Player(props) {
  return JsxRuntime.jsx("div", {
    className: "mt-5",
    dangerouslySetInnerHTML: {
      __html: `<iframe frameborder="0" loading="lazy" id="ausha-Q0Lh" height="420" style="border: none; width:100%; height:420px" src="https://player.ausha.co/index.html?showId=od2PjTvjJpwV&color=%239b4d1c&playlist=true&v=3&playerId=ausha-Q0Lh"></iframe><script src="https://player.ausha.co/ausha-player.js"></script>`
    }
  });
}

function Index$Icon(props) {
  return JsxRuntime.jsx("a", {
    children: JsxRuntime.jsx("img", {
      src: props.src
    }),
    className: "w-16 m-2 opacity-75 hover:opacity-50 text-red-500",
    href: props.url,
    target: "_blank"
  });
}

function makeIcon(src, url, key) {
  return JsxRuntime.jsx(Index$Icon, {
    src: src,
    url: url
  }, key);
}

let siteName = `Goûtues - Podcast`;

function $$default(param) {
  let val;
  try {
    val = S.parseJsonOrThrow(param.show, Api.Shows.SingleById.schema);
  } catch (raw_error) {
    let error = Primitive_exceptions.internalToException(raw_error);
    if (error.RE_EXN_ID === S.$$Error) {
      console.error(error._1);
      return JsxRuntime.jsx(Index$P, {
        children: Utils.s("Il y a eu un problème lors de la récupération des informations. Veuillez recharger la page.")
      });
    }
    throw error;
  }
  let match = val.data;
  let image_url = match.image_url;
  let description = match.description;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs(Head, {
        children: [
          JsxRuntime.jsx("title", {
            children: Utils.s(siteName)
          }),
          JsxRuntime.jsx("meta", {
            content: "width=device-width, initial-scale=1",
            name: "viewport"
          }),
          JsxRuntime.jsx("meta", {
            charSet: "utf-8"
          }),
          JsxRuntime.jsx("meta", {
            content: description,
            name: "description"
          }),
          JsxRuntime.jsx("meta", {
            content: siteName,
            property: "og:title"
          }, "ogtitle"),
          JsxRuntime.jsx("meta", {
            content: image_url,
            property: "og:image"
          }, "ogimage"),
          JsxRuntime.jsx("meta", {
            content: siteName,
            property: "og:site_name"
          }, "ogsitename"),
          JsxRuntime.jsx("meta", {
            content: description,
            property: "og:description"
          }, "ogdesc"),
          JsxRuntime.jsx("meta", {
            content: "summary",
            name: "twitter:card"
          }, "twcard")
        ]
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: Utils.s(`Retrouvez-nous sur toutes ces plateformes`),
            className: "text-3xl mx-5 font-display font-bold text-center text-gray-700"
          }),
          JsxRuntime.jsx("div", {
            children: Stdlib_Array.filterMap(match.listening_links.data, param => {
              let url = param.url;
              let key = param.key;
              switch (key) {
                case "deezer" :
                  return makeIcon("static/deezer.svg", url, key);
                case "itunes" :
                  return makeIcon("static/apple-podcasts.png", url, key);
                case "soundcloud" :
                  return makeIcon("static/soundcloud.svg", url, key);
                case "spotify" :
                  return makeIcon("static/spotify.svg", url, key);
                default:
                  return;
              }
            }),
            className: "flex flex-row justify-center my-5"
          })
        ],
        className: "justify-center my-5"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("img", {
            className: "md:w-1/3 md:max-w-lg",
            src: image_url
          }),
          JsxRuntime.jsx("div", {
            className: "space-y-5 mx-2 md:mx-0 my-10 md:my-5 md:w-2/3 md:mr-12 text-justify text-gray-700",
            dangerouslySetInnerHTML: {
              __html: match.html_description
            }
          })
        ],
        className: "flex flex-col md:flex-row-reverse items-center px-2"
      }),
      JsxRuntime.jsx(Index$Player, {})
    ],
    className: "flex flex-col"
  });
}

async function getServerSideProps(_ctx) {
  let show = await Api.Shows.SingleById.get();
  return {
    props: {
      show: show
    }
  };
}

export {
  $$default as default,
  siteName,
  getServerSideProps,
}
/* S Not a pure module */
