// Generated by ReScript, PLEASE EDIT WITH CARE


let Req = {};

let Res = {};

let GetServerSideProps = {
  Req: Req,
  Res: Res
};

let GetStaticProps = {};

let GetStaticPaths = {};

let Link = {};

let Events = {};

let Router = {
  Events: Events
};

let Head = {};

let $$Error = {};

let Dynamic = {};

export {
  GetServerSideProps,
  GetStaticProps,
  GetStaticPaths,
  Link,
  Router,
  Head,
  $$Error,
  Dynamic,
}
/* No side effect */
